src/CI/InventoryBundle/Entity/ActivityLog.php
<?php

namespace CI\InventoryBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContextInterface;

/**
 * ActivityLog
 *
 * @ORM\Table(name="activity_log")
 * @ORM\Entity(repositoryClass="CI\InventoryBundle\Entity\ActivityLogRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class ActivityLog
{
	const ACTION_CREATE = 'create';
	const ACTION_UPDATE = 'update';
	const ACTION_DELETE = 'delete';
	
	/**
	 * @var integer
	 *
	 * @ORM\Column(name="id", type="integer")
	 * @ORM\Id
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	private $id;
	
	/**
	 * @var \DateTime
	 *
	 * @ORM\Column(name="timestamp", type="datetime")
	 */
	private $timestamp;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="action", type="string", length=6)
	 * @Assert\Type(type="string")
	 * @Assert\Choice(choices = {"create", "update", "delete"})
	 */
	private $action;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="user", type="string", length=255)
	 * @Assert\Type(type="string")
	 */
	private $user;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="class", type="string", length=255)
	 * @Assert\Type(type="string")
	 */
	private $class;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="name", type="string", length=255)
	 * @Assert\Type(type="string")
	 */
	private $name;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="route_name", type="string", length=255)
	 * @Assert\Type(type="string")
	 */
	private $routeName;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="entity_id", type="integer")
	 * @Assert\Type(type="integer")
	 */
	private $entityId;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set timestamp
     *
     * @param \DateTime $timestamp
     * @return EntityAudit
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;
    
        return $this;
    }

    /**
     * Get timestamp
     *
     * @return \DateTime 
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Set action
     *
     * @param string $action
     * @return EntityAudit
     */
    public function setAction($action)
    {
        $this->action = $action;
    
        return $this;
    }

    /**
     * Get action
     *
     * @return string 
     */
    public function getAction()
    {
        return $this->action;
    }
    
    /**
     * Set user
     *
     * @param string $user
     * @return EntityAudit
     */
    public function setUser($user)
    {
    	$this->user = $user;
    
    	return $this;
    }
    
    /**
     * Get user
     *
     * @return string
     */
    public function getUser()
    {
    	return $this->user;
    }
    
    /**
     * Set class
     *
     * @param string $class
     * @return ActivityLog
     */
    public function setClass($class)
    {
    	$this->class = $class;
    
    	return $this;
    }
    
    /**
     * Get class
     *
     * @return string
     */
    public function getClass()
    {
    	return $this->class;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return EntityAudit
     */
    public function setName($name)
    {
        $this->name = $name;
    
        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set routeName
     *
     * @param string $routeName
     * @return EntityAudit
     */
    public function setRouteName($routeName)
    {
        $this->routeName = $routeName;
    
        return $this;
    }

    /**
     * Get routeName
     *
     * @return string 
     */
    public function getRouteName()
    {
        return $this->routeName;
    }

    /**
     * Set entityId
     *
     * @param integer $entityId
     * @return EntityAudit
     */
    public function setEntityId($entityId)
    {
        $this->entityId = $entityId;
    
        return $this;
    }

    /**
     * Get entityId
     *
     * @return integer 
     */
    public function getEntityId()
    {
        return $this->entityId;
    }
    
    public function getClassDisplay()
    {
    	return strtolower(preg_replace('/(?<!\ )[A-Z]/', ' $0', $this->getClass()));
    }
}

src/CI/InventoryBundle/Controller/ActivityLogController.php
<?php
namespace CI\InventoryBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\PreAuthorize;

/**
 * EntityAudit controller
 *
 * @Route("/activity-log")
 * @PreAuthorize("hasRole('ROLE_ADMIN')")
 */
class ActivityLogController extends Controller
{
	/**
	 * Activity Log
	 *
	 * @Route("/", name="activitylog")
	 * @Method("GET")
	 * @Template()
	 */
	public function indexAction()
	{
		$paginator = $this->get('knp_paginator');
		$pagination = $paginator->paginate(
			$this->getDoctrine()->getManager()->getRepository('CIInventoryBundle:ActivityLog')->findAll(),
			$this->get('request')->query->get('page', 1),
			$this->container->getParameter('pagination_limit_per_page')
		);
		
		return array(
			'pagination' => isset($pagination) ? $pagination : null 
		);
	}
}

src/CI/InventoryBundle/Resources/views/ActivityLog/index.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}
{% import 'CIInventoryBundle:Misc:macros.html.twig' as macros %}

{% block breadcrumbs %}
<li>Admin</li>
<li class="active">Activity Logs</li>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>{{ FAIcon('info', 'page-header-icon') }} Activity Logs</h1>
		</div>
		
		{% if pagination.getPaginationData['totalCount'] > 0 %}
			<div id="display-count" class="pull-right">
				{{ macros.paginationCount(pagination) }}
			</div>
			
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th class="col-md-12">Logs</th>
						</tr>
					</thead>
					<tbody>
					{% for entity in pagination %}
						{% set link = entity.name %}
						{% if pathExists(entity.routeName) %}
							{% set link = "<a href='" ~ path(entity.routeName, {'id':entity.entityId}) ~ "'>" ~ entity.name ~ "</a>" %}
						{% endif %}
						<tr>
							<td>
								<strong>{{ entity.user }}</strong> has <strong>{{ entity.action ~ 'd' }}</strong> {{ entity.classDisplay }} <strong>{{ link|raw }}</strong>. <small class="text-muted timeago" title="{{ entity.timestamp|date('F d, Y g:i:s a') }}">{{ entity.timestamp|date('F d, Y \\a\\t g:i:s a') }}</small>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="pull-right">
				{{ knp_pagination_render(pagination) }}
			</div>	
		{% else %}
			<div class="alert">
				No logs.
			</div>
		{% endif %}
	</div>
</div>
{% endblock content %}