src/CI/InventoryBundle/Entity/UmReport.php
<?php

namespace CI\InventoryBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\ExecutionContextInterface;
use CI\InventoryBundle\Helper\ApiUploadedFile;

/**
 * InventoryReport
 *
 * @ORM\Table(name="um_report")
 * @ORM\Entity(repositoryClass="CI\InventoryBundle\Entity\UmReportRepository")
 * @ORM\HasLifecycleCallbacks()
 * @Assert\Callback(methods={"validate"})
 */
class UmReport extends BaseEntity
{
	/**
	 * @var date
	 *
	 * @ORM\Column(name="report_date", type="date")
	 * @Assert\NotBlank(message="Report date is required.")
	 * @Assert\Date(message="Report date is not a valid date.")
	 */
	private $reportDate;
	
	/**
	 * @var date
	 *
	 * @ORM\Column(name="report_creation_date", type="date")
	 * @Assert\NotBlank(message="Report creation date is required.")
	 * @Assert\Date(message="Report creation date is not a valid date.")
	 */
	private $reportCreationDate;
	
	/**
	 * @var date
	 *
	 * @ORM\Column(name="report_last_updated_date", type="date", nullable=true)
	 * @Assert\Date(message="Report last updated date is not a valid date.")
	 */
	private $reportLastUpdatedDate;
	
	/**
	 * @var string
	 *
	 * @ORM\Column(name="note", type="text", nullable=true)
	 * @Assert\Type(type="string")
	 */
	private $note;
	
	/**
	 * @ORM\Column(type="string", length=255, nullable=true)
	 * @Assert\Type(type="string")
	 * @Assert\Length(max=255)
	 */
	private	$path;
	
	/**
	 * @Assert\File(maxSize="150M")
	 */
	private $file;
	
	private $temp;
	
	/**
	 * @ORM\ManyToOne(targetEntity="Device", inversedBy="inventoryReports")
	 * @Assert\NotBlank(message="Device is required.")
	 */
	private $device;
	
	/**
	 * @ORM\ManyToOne(targetEntity="Store", inversedBy="inventoryReports")
	 * @Assert\NotBlank(message="Store is required.")
	 */
	private $store;
	
	/**
	 * @ORM\OneToMany(targetEntity="UmReportItem", mappedBy="inventoryReport", cascade={"persist", "remove"})
	 * @Assert\Count(min="1", minMessage="At least one product is required.")
	 * @Assert\Valid
	 */
	private $items;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->items = new ArrayCollection();
    }
    
    /**
     * Set path
     *
     * @param string $path
     * @return InventoryReport
     */
    public function setPath($path)
    {
    	$this->path = $path;
    
    	return $this;
    }
    
    /**
     * Get path
     *
     * @return string
     */
    public function getPath()
    {
    	return $this->path;
    }
    
    /**
     * Set note
     *
     * @param string $note
     * @return InventoryReport
     */
    public function setNote($note)
    {
    	$this->note = $note;
    
    	return $this;
    }
    
    /**
     * Get note
     *
     * @return string
     */
    public function getNote()
    {
    	return $this->note;
    }
    
    /**
     * Set reportDate
     *
     * @param \DateTime $reportDate
     * @return InventoryReport
     */
    public function setReportDate($reportDate)
    {
        $this->reportDate = $reportDate;
    
        return $this;
    }

    /**
     * Get reportDate
     *
     * @return \DateTime 
     */
    public function getReportDate()
    {
        return $this->reportDate;
    }
    
    /**
     * Set reportCreationDate
     *
     * @param \DateTime $reportCreationDate
     * @return InventoryReport
     */
    public function setReportCreationDate($reportCreationDate)
    {
    	$this->reportCreationDate = $reportCreationDate;
    
    	return $this;
    }
    
    /**
     * Get reportCreationDate
     *
     * @return \DateTime
     */
    public function getReportCreationDate()
    {
    	return $this->reportCreationDate;
    }
    
    /**
     * Set reportLastUpdatedDate
     *
     * @param \DateTime $reportLastUpdatedDate
     * @return InventoryReport
     */
    public function setReportLastUpdatedDate($reportLastUpdatedDate)
    {
    	$this->reportLastUpdatedDate = $reportLastUpdatedDate;
    
    	return $this;
    }
    
    /**
     * Get reportLastUpdatedDate
     *
     * @return \DateTime
     */
    public function getReportLastUpdatedDate()
    {
    	return $this->reportLastUpdatedDate;
    }
    
    /**
     * Set device
     *
     * @param \CI\InventoryBundle\Entity\Device $device
     * @return InventoryReport
     */
    public function setDevice(\CI\InventoryBundle\Entity\Device $device = null)
    {
    	$this->device = $device;
    
    	return $this;
    }
    
    /**
     * Get device
     *
     * @return \CI\InventoryBundle\Entity\Device
     */
    public function getDevice()
    {
    	return $this->device;
    }

    /**
     * Set store
     *
     * @param \CI\InventoryBundle\Entity\Store $store
     * @return InventoryReport
     */
    public function setStore(\CI\InventoryBundle\Entity\Store $store = null)
    {
        $this->store = $store;
    
        return $this;
    }

    /**
     * Get store
     *
     * @return \CI\InventoryBundle\Entity\Store 
     */
    public function getStore()
    {
        return $this->store;
    }

    /**
     * Add items
     *
     * @param \CI\InventoryBundle\Entity\UmReportItem $items
     * @return InventoryReport
     */
    public function addItem(\CI\InventoryBundle\Entity\UmReportItem $items)
    {
    	$items->setInventoryReport($this);
        $this->items[] = $items;
    
        return $this;
    }

    /**
     * Remove items
     *
     * @param \CI\InventoryBundle\Entity\UmReportItem $items
     */
    public function removeItem(\CI\InventoryBundle\Entity\UmReportItem $items)
    {
        $this->items->removeElement($items);
    }

    /**
     * Get items
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getItems()
    {
        return $this->items;
    }
    
    /**
     * Sets file.
     *
     * @param ApiUploadedFile $file
     */
    public function setFile(ApiUploadedFile $file = null)
    {
    	$this->file = $file;
    	// check if we have an old image path
    	if (is_file($this->getAbsolutePath())) {
    		// store the old name to delete after the update
    		$this->temp = $this->getAbsolutePath();
    	} else {
    		$this->path = 'initial';
    	}
    }
    
    /**
     * Get file.
     *
     * @return ApiUploadedFile
     */
    public function getFile()
    {
    	return $this->file;
    }
    
    public function getAbsolutePath()
    {
    	return null === $this->path ? null : $this->getUploadRootDir() . '/' . $this->path;
    }
    
    public function getWebPath()
    {
    	return null === $this->path ? null : $this->getUploadDir() . '/' . $this->path;
    }
    
    protected function getUploadRootDir()
    {
    	return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }
    
    protected function getUploadDir()
    {
    	return 'uploads/inventory-report/' . $this->getId();
    }
    
    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
    	if (null !== $this->getFile()) {
    		// do whatever you want to generate a unique name
    		$filename = sha1(uniqid(mt_rand(), true));
    		$this->path = $filename . '.' . $this->getFile()->guessExtension();
    	}
    }
    
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
    	if (null === $this->getFile()) {
    		return;
    	}
    	 
    	$this->getFile()->move($this->getUploadRootDir(), $this->path);
    	 
    	// check if we have an old image
    	if (isset($this->temp)) {
    		// delete the old image
    		unlink($this->getUploadRootDir().'/'.$this->temp);
    		// clear the temp image path
    		$this->temp = null;
    	}
    	$this->file = $this->getUploadRootDir().'/'.$this->path;
    }
    
    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
    	$file = $this->getAbsolutePath();
    	if ($file) {
    		unlink($file);
    	}
    }
    
    public function validate(ExecutionContextInterface $context)
    {
    	if (!$this->getReportCreationDate()) {
    		$context->addViolationAt('reportCreationDate', 'Report creation date is required.');
    	}
    
    	if (!$this->getCreatedBy()) {
    		$context->addViolationAt('createdBy', 'Username is required.');
    	}
    	
    	if ($this->file) {
    		if (!file_exists($this->file->getPathname())) {
    			$context->addViolationAt('file', 'Image not found.');
    		}
    	
    		if (!in_array($this->file->guessExtension(), array('jpg', 'png', 'jpeg'))) {
    			$context->addViolationAt('file', 'Only .jpg, .png and .jpeg images are allowed.');
    		}
    	}
    }
    
    public function getLog()
    {
    	return array(
    		'Device' => $this->getDevice()->getName(),
    		'Store' => $this->getStore()->getName(),
    		'Report Date' => $this->getReportDate(),
    		'Note' => $this->getNote(),
    		'Report Creation Date' => $this->getReportCreationDate(),
    		'Report Last Updated Date' => $this->getReportLastUpdatedDate()
    	);
    }
}

src/CI/InventoryBundle/Controller/UppermanagementController.php
<?php

namespace CI\InventoryBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\PreAuthorize;
use PHPExcel;
use PHPExcel_IOFactory;
use CI\CoreBundle\Entity\User;
use CI\InventoryBundle\Form\Type\UmReportFilterType;

/**
 * InventoryReport controller
 *
 * @Route("/upperm")
 */
class UppermanagementController extends Controller
{

    /**
     * @Route("/", name="upperm")
     * @Method("GET")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $form = $this->createForm(new UmReportFilterType($this->get('security.context')));

        if ($form->handleRequest($request)->isSubmitted())
        {
            if ($form->isValid())
            {
                $params = $form->getData();
                $params = $this->prepareParams($params);

                $qb = $em->getRepository('CIInventoryBundle:UmReport')->findAllUMReport($params);
            } else
            {
                $this->get('session')->getFlashBag()->add('danger', 'Please try again.');
            }
        }

        if (isset($qb))
        {
            $paginator = $this->get('knp_paginator');
            $pagination = $paginator->paginate(
                    $qb, $this->get('request')->query->get('page', 1), $this->container->getParameter('pagination_limit_per_page'), array('distinct' => true)
            );
        }

        return array(
            'params' => isset($params) ? $params : null,
            'pagination' => isset($pagination) ? $pagination : null,
            'search_form' => $form->createView(),
        );
    }

    private function prepareParams(array $params)
    {
        $sc = $this->get('security.context');

        if (!$sc->isGranted(User::ROLE_ADMIN))
        {
            if ($sc->isGranted(User::ROLE_RSM))
            {
                $params['rsm'] = $this->getUser();
            } else if ($sc->isGranted(User::ROLE_CDM))
            {
                $params['cdm'] = $this->getUser();
            } else if ($sc->isGranted(User::ROLE_TL))
            {
                $params['tl'] = $this->getUser();
            } else if ($sc->isGranted(User::ROLE_DISER))
            {
                $params['diser'] = $this->getUser();
            }
        }

        return $params;
    }
    
       /**
	 * @Route("/export/xls", name="umreport_export_xls")
	 * @PreAuthorize("hasAnyRole('ROLE_RSM', 'ROLE_CDM', 'ROLE_TL')")
	 */
	public function exportXLSAction(Request $request)
	{
		$em = $this->getDoctrine()->getManager();
		$form = $this->createForm(new UmReportFilterType($this->get('security.context')));
		$form->handleRequest($request);
		$params = $form->getData();
		$params = $this->prepareParams($params);
		
		$objPHPExcel = new PHPExcel();
		
		$fontStyle = array('bold' => true);
		
		$styleArray = array(
			'font' => $fontStyle,
			'alignment' => array('horizontal' => \PHPExcel_Style_Alignment::HORIZONTAL_CENTER)
		);
		
		$objPHPExcel->getProperties()->setCreator("ISCI")->setTitle("Upper Management Report");
		
		$xls = $objPHPExcel->setActiveSheetIndex(0);
		
		$xls->getColumnDimension("A")->setAutoSize(true); $xls->getColumnDimension("B")->setAutoSize(true);
		$xls->getColumnDimension("C")->setAutoSize(true); $xls->getColumnDimension("D")->setAutoSize(true);
		$xls->getColumnDimension("E")->setAutoSize(true);
		
		$reports = $em->getRepository("CIInventoryBundle:UmReport")->findAllUMReport($params)->getResult();
		
		$counter = 1;
		foreach($reports as $report) {
			$xls->setCellValue('A' . $counter, 'Report ID');
			$xls->setCellValue('B' . $counter, 'Device ID');
			$xls->setCellValue('C' . $counter, 'Branch');
			$xls->setCellValue('D' . $counter, 'Dates');
			$xls->setCellValue('E' . $counter, 'Username');
			$xls->getStyle("A" . $counter . ":E" . $counter)->applyFromArray($styleArray + array('borders' => array('top' => array('style' => \PHPExcel_Style_Border::BORDER_THIN))));
			$counter++;
			
			$date = "Report Date: " . $report->getReportDate()->format('M. d, Y') . "\n" .
					"Creation Date: " . $report->getReportCreationDate()->format('M. d, Y') . "\n" .
					"Upload Date: " . $report->getCreatedAt()->format('M. d, Y');

			if ($report->getReportLastUpdatedDate()) {
				$date .= "\nLast Updated Date: " . $report->getReportLastUpdatedDate()->format('M. d, Y');
			}
			
			$xls->setCellValue('A' . $counter, $report->getId() . "\n" . $report->getNote());
			$xls->getStyle('A' . $counter)->getAlignment()->setHorizontal(\PHPExcel_Style_Alignment::HORIZONTAL_LEFT)->setWrapText(true);
			$xls->setCellValue('B' . $counter, $report->getDevice()->getDeviceId());
			$xls->setCellValue('C' . $counter, $report->getStore()->getName());
			$xls->setCellValue('D' . $counter, $date);
			$xls->getStyle('D' . $counter)->getAlignment()->setWrapText(true);
//			$xls->setCellValue('E' . $counter, $report->getCreatedBy());
			$xls->setCellValue('E' . $counter, $report->getDevice()->getPersonInCharge()->getUsername());
			$counter++;
			
			$xls->setCellValue('A' . $counter, 'Products');
			$counter++;
			$xls->setCellValue('A' . $counter, 'Name');
			$xls->setCellValue('B' . $counter, 'Available');
			$xls->setCellValue('C' . $counter, 'Count');
			$xls->setCellValue('D' . $counter, 'Note');
			$xls->getStyle("A" . ($counter - 1) . ":D" . $counter)->applyFromArray($styleArray);
			$counter++;
			
			foreach($report->getItems() as $item) {
				$xls->setCellValue('A' . $counter, $item->getProduct()->getName());
				$xls->setCellValue('B' . $counter, $item->getAvailable() ? 'Yes' : 'No');
				$count = $item->getCount() ? number_format($item->getCount(), 2) : 'No Input';
				$xls->setCellValue('C' . $counter, $count);
				$xls->getStyle('C' . $counter)->getNumberFormat()->setFormatCode('#,##0.00;[Red](#,##0.00)');
				$xls->setCellValue('D' . $counter, $item->getNote());
				$counter++;
			}
			$counter++;
		}
		
		$xls->setSelectedCell();
		
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
	
		$response = new Response();
		$response->headers->set('Content-Type', 'application/vnd.ms-excel');
	
		$filename = 'UM_Report_' . date('M-d-Y');
	
		$response->headers->set('Content-Disposition', 'attachment;filename='. $filename . '.xls');
		$response->headers->set('Cache-Control', 'ax-age=0');
		$response->sendHeaders();
	
		$objWriter->save('php://output');
		exit();
	}

}

src/CI/InventoryBundle/Resources/views/Uppermanagement/index.html.twig
{% extends 'CICoreBundle::layout.html.twig' %}
{% import 'CIInventoryBundle:Misc:macros.html.twig' as macros %}

{% block breadcrumbs %}
<li>Reports</li>
<li class="active"> UM Store Visit Report </li>
{% endblock %}

{% block content %}                 
         <div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<div class="col-md-10">
				<h1>{{ FAIcon('file', 'page-header-icon') }} UM Store Visit Report </h1>
				<p>Shows details of visit for each branch.</p>
			</div>
			
			{% if params %}
				{% set exportParams = {} %}
				
				{% if params.rsm is defined and params.rsm %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[rsm]' : params.rsm.id }) %}
				{% endif %}
				
				{% if params.cdm is defined and params.cdm %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[cdm]' : params.cdm.id }) %}
				{% endif %}
				
				{#{% if params.tl is defined and params.tl %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[tl]' : params.tl.id }) %}
				{% endif %}#}
				
				{#{% if params.diser is defined and params.diser %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[diser]' : params.diser.id }) %}
				{% endif %}#}
				
				{#{% if params.productClassification %}
					{% for pc in params.productClassification %}
						{% set exportParams = exportParams | merge({ ('ci_inventorybundle_umreportfilter[productClassification][' ~ loop.index0 ~ ']') : pc }) %}
					{% endfor %}
				{% endif %}#}
				
				{#{% if params.reportId %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[reportId]' : params.reportId }) %}
				{% endif %}
				
				{% if params.deviceId %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[deviceId]' : params.deviceId }) %}
				{% endif %}#}
				
				{% if params.store %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[store]' : params.store.id }) %}
				{% endif %}
				
				{% if params.product %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[product]' : params.product.id }) %}
				{% endif %}
				
				{% if params.dateFrom %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[dateFrom]' : params.dateFrom|date('m/d/Y') }) %}
				{% endif %}
				
				{% if params.dateTo %}
					{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[dateTo]' : params.dateTo|date('m/d/Y') }) %}
				{% endif %}

				{#{% if params.chain %}
						{% set exportParams = exportParams | merge({ 'ci_inventorybundle_umreportfilter[chain]' : params.chain.name }) %}
					{% endif %}#}
                                        
                                        
				
				<div class="col-md-2">
					<a class="btn btn-default btn-labeled btn-sm pull-right" href="{{ path('umreport_export_xls', exportParams) }}">{{ FAIcon('file-excel-o', 'btn-label') }} Export to XLS</a> 
				</div>
			{% endif %}
		</div>
		<!-- search form -->
		<div class="row search-filters">
			{{ form_start(search_form, {'action': path('upperm'), 'method': 'GET', 'attr': {'class': 'form-horizontal', 'novalidate': 'novalidate'} }) }}
				{{ bootstrap_set_style('horizontal') }}
				<div class="col-md-5">
					{% if search_form.rsm is defined %}
						{{ form_row(search_form.rsm) }}
					{% endif %}
					{% if search_form.cdm is defined %}
                                            {{ form_row(search_form.cdm) }}
					{% endif %}
					{#{% if search_form.tl is defined %}
						{{ form_row(search_form.tl) }}
					{% endif %}
					{% if search_form.diser is defined %}
						{{ form_row(search_form.diser) }}
					{% endif %}
					{{ form_row(search_form.reportId) }}
					{{ form_row(search_form.deviceId) }}#}
					
				</div>
				<div class="col-md-5">
					{{ form_row(search_form.store) }}
					{{ form_row(search_form.product) }}
					{#{{ form_row(search_form.productClassification) }}
					{{ form_row(search_form.storeClassification) }}
                                        {{ form_row(search_form.chainClassification) }}
                                        {{ form_row(search_form.productClassification) }}#}
					{{ form_row(search_form.dateFrom) }}
					{{ form_row(search_form.dateTo) }}
                                        {{ form_row(search_form.search) }}
				</div>
			{{ form_end(search_form) }}
		</div>
		<!-- end of search form -->               
                     
                
                {% if pagination and pagination.getPaginationData['totalCount'] > 0 %}
			<div id="display-count" class="pull-right">
				{{ macros.paginationCount(pagination) }}
			</div>
			
			<div class="table-responsive">
				<table class="table table-hover">
					<thead>
						<tr>
							<th class="col-md-1">{{ utils.sortableTableHeader(pagination, 'ir.id', 'Report ID') }}</th>
							<th class="col-md-1">Device ID</th>
{#                                                       <th class="col-md-2">Chain</th>#}
							<th class="col-md-2">{{ utils.sortableTableHeader(pagination, 's.name', 'Branch') }}</th>
                                                        <th class="col-md-1">Notes</th>
                                                       <th class="col-md-1">Photo</th>
							<th class="col-md-3">{{ utils.sortableTableHeader(pagination, 'ir.reportDate', 'Dates (Sorts Report Date)') }}</th>
							<th class="col-md-1">Username</th>
							<th class="col-md-4">Product</th>
						</tr>
					</thead>
					<tbody>
					{% for entity in pagination %}
						<tr>
							<td>{{ entity.id }}</td>
							<td>{{ entity.device.deviceId }}</td>
{#                                                            <td>{{ entity.store.chain.name }}</td>#}
							<td>
								{{ entity.store.name }}
{#								{% if entity.note %}<br><small class="text-muted">{{ entity.note|nl2br }}</small>{% endif %}#}
							</td>
                                                        
						<td>
                                                        {% if entity.note %}<br>{{ entity.note|nl2br }}{% endif %}
							</td>
                                                         <td>
                                                        {% if entity.path %}
                                                           
                                                            <a href="{{ asset(entity.webPath) }}" class="btn btn-outline btn-default btn-xs" target="__blank">{{ FAIcon('paperclip') }}</a>
{#<a href="{{ asset(entity.webPath) }}" class="btn btn-outline btn-default btn-xs" target="__blank">
 <img src="{{ asset(entity.webPath) }}" height="50%" alt="my alt of image" /></a>#}
                                                                                                                   {% endif %}
                                                        </td>
								
                                                        
                                                        
							<td>
								Report Date: <strong class="pull-right">{{ utils.formatDate(entity.reportDate) }}</strong><br>
								Creation Date: <strong class="pull-right">{{ utils.formatDate(entity.reportCreationDate) }}</strong><br>
								Upload Date: <strong class="pull-right">{{ utils.formatDate(entity.createdAt) }}</strong>
								{% if entity.reportLastUpdatedDate %}<br>Last Updated Date: <strong class="pull-right">{{ utils.formatDate(entity.reportLastUpdatedDate) }}</strong>{% endif %}
							</td>
{#							<td>{{ entity.createdBy }}</td>#}
                                                        <td>{{ entity.device.personInCharge.username  }}</td>
                                                    
                                                      

							<td>
								<ul>
								{% for item in entity.items %}
									{% set product = item.path ? '<a href="' ~ asset(item.getWebPath) ~ '" target="__blank">' ~ item.product.name ~ '</a>' : item.product.name %}
									<li>
										{{ product|raw }}<br>
										<small class="text-muted">Available: {{ item.available ? 'Yes' : 'No' }} - Count: {% if item.count %}{{ item.count|decimal(2) }}{% else %}No Input{% endif %}</small>
										{% if item.note %}<br><small class="text-muted">{{ item.note|nl2br }}</small>{% endif %}
									</li>
								{% endfor %}
								</ul>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
			</div>
			<div class="pull-right">
				{{ knp_pagination_render(pagination) }}
			</div>	
		{% elseif params %}
			<div class="alert">
				No results found.
			</div>
		{% endif %}
	</div>
</div>
                        
{% endblock content %}

{% block javascripts %}
<script>
$(function(){
	$( ".input-group.date" ).datepicker({
		changeMonth: true,
		changeYear: true,
		autoclose: true, 
		todayHighlight: true,
	});
        $( ".input-group.date" ).on('change',function(){
            var from = new Date($('#ci_inventorybundle_inventoryreportfilter_dateFrom').val());
            var to = new Date($('#ci_inventorybundle_inventoryreportfilter_dateTo').val());
            
         if(to < from)
         {
         $('#ci_inventorybundle_inventoryreportfilter_dateTo').val('');
         }

        });
});
</script>
{% endblock %}